### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by bunyk** [vshymanskyy/blynk-pc-remote#1]
```
$ npm install -g blynk-pc-remote
/home/bunyk/.nvm/versions/node/v7.5.0/bin/blynk-pc-remote -> /home/bunyk/.nvm/versions/node/v7.5.0/lib/node_modules/blynk-pc-remote/bin/blynk-pc-remote.js

> robotjs@0.4.5 install /home/bunyk/.nvm/versions/node/v7.5.0/lib/node_modules/blynk-pc-remote/node_modules/robotjs
> prebuild --install

prebuild WARN install No prebuilt binaries found (target=v7.5.0 arch=x64 platform=linux)
make: Entering directory '/home/bunyk/.nvm/versions/node/v7.5.0/lib/node_modules/blynk-pc-remote/node_modules/robotjs/build'
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
cc1plus: warning: command line option ‘-Wbad-function-cast’ is valid for C/ObjC but not for C++
In file included from ../src/keypress.h:6:0,
                 from ../src/robotjs.cc:7:
../src/keycode.h:102:23: fatal error: X11/Xutil.h: No such file or directory
compilation terminated.
robotjs.target.mk:113: recipe for target 'Release/obj.target/robotjs/src/robotjs.o' failed
make: *** [Release/obj.target/robotjs/src/robotjs.o] Error 1
make: Leaving directory '/home/bunyk/.nvm/versions/node/v7.5.0/lib/node_modules/blynk-pc-remote/node_modules/robotjs/build'
prebuild ERR! build error 
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/home/bunyk/.nvm/versions/node/v7.5.0/lib/node_modules/blynk-pc-remote/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! stack     at emitTwo (events.js:106:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:192:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/home/bunyk/.nvm/versions/node/v7.5.0/lib/node_modules/blynk-pc-remote/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:192:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
/home/bunyk/.nvm/versions/node/v7.5.0/lib
└── (empty)

npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/home/bunyk/.nvm/versions/node/v7.5.0/bin/node" "/home/bunyk/.nvm/versions/node/v7.5.0/bin/npm" "install" "-g" "blynk-pc-remote"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! robotjs@0.4.5 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the robotjs@0.4.5 install script 'prebuild --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the robotjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs robotjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls robotjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bunyk/npm-debug.log
```

**Comment by bunyk** [comment]
Possible fix (http://stackoverflow.com/questions/5299989/x11-xlib-h-not-found-in-ubuntu ):

```
sudo apt-get install libx11-dev
```

**Comment by bunyk** [comment]
And now I have:

```
../src/mouse.c:12:35: fatal error: X11/extensions/XTest.h: No such file or directory
```

**Comment by bunyk** [comment]
```
sudo apt-get install libxtst-dev
```

And it works. 

I suggest to add 
```
sudo apt-get install libx11-dev libxtst-dev
```
somewhere into readme. Probably there are requirements of other packages, I already have.
